[package]
name = "example"
version = "0.1.1"
authors = ["Daniele Esposti"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
openstreetmap-api = { path = ".." }
tokio = { version = "1.15", features = ["full"] }
